# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add forms capability
[build.processing.html]
  pretty_urls = true

# Ensure forms are properly processed
[dev]
  command = "npm run dev"
  framework = "#custom"
  port = 5173
  targetPort = 5173